=== UM-LPM/server/infra/domain.dtd
<!ELEMENT domain (name, memory, vcpu, cpu?, disk*, network-interface*, direct-interface*, spice?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT memory (#PCDATA)>
<!ATTLIST memory
    unit CDATA #IMPLIED
>
<!ELEMENT vcpu (#PCDATA)>

<!ELEMENT cpu EMPTY>
<!ATTLIST cpu
    mode CDATA #IMPLIED
>

<!ELEMENT disk EMPTY>
<!ATTLIST disk
    pool CDATA #REQUIRED
    volume CDATA #REQUIRED
>

<!ELEMENT network-interface EMPTY>
<!ATTLIST network-interface
    network CDATA #REQUIRED
    mac CDATA #REQUIRED
>

<!ELEMENT direct-interface EMPTY>
<!ATTLIST direct-interface
    dev CDATA #REQUIRED
>

<!ELEMENT spice EMPTY>

=== UM-LPM/server/infra/mihaelhpc/mihaelhpc.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../domain.xsl"?>
<!DOCTYPE domain SYSTEM '../domain.dtd'>

<domain>
	<name>mihaelhpc</name>
    <memory unit="G">100</memory>
    <vcpu>32</vcpu>
    <cpu>
        <topology sockets='2' cores='8' threads='2'/>
    </cpu>
    <disk pool='images' volume='mihaelhpc.qcow2'/>
    <network-interface
       network='private-network' 
       mac='02:4a:24:fe:f5:39'/>
	<spice />
</domain>
